openapi: 3.0.3
info:
  title: Merchant APIs
  description: |-
    universalmacro
  contact:
    email: chenyunda218@gmail.com
  version: 0.0.3
servers:
  - url: https://uat.uat-hongkong-1-merchant.universalmacro.com
tags:
  - name: Merchant
  - name: Session
  - name: Member
  - name: Verification
  - name: Order
  - name: Space
paths:
  /sessions:
    post:
      tags:
        - Session
      summary: 'Create session'
      operationId: CreateSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRequest'
      responses:
        '201':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
  /merchants/self:
    get:
      tags:
        - Merchant
      summary: 'Get self merchant'
      operationId: GetSelfMerchant
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
  /merchants/self/members:
    get:
      tags:
        - Merchant
      summary: 'Get self merchant'
      operationId: ListSelfMembers
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberList'
  /merchants/self/contact-form:
    get:
      tags:
        - Merchant
      summary: 'Get self merchant'
      operationId: ListSelfContactForm
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFormList'
  /merchants/self/contact-form/{id}:
    get:
      tags:
        - Merchant
      summary: 'Get self merchant'
      operationId: GetSelfContactForm
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactForm'
    delete:
      tags:
        - Merchant
      summary: 'Delete self merchant'
      operationId: DeleteSelfContactForm
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '204':
          description: 'Success'
  /merchants:
    get:
      tags:
        - Merchant
      summary: 'List merchants'
      operationId: ListMerchants
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/Ordering'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantList'
    post:
      tags:
        - Merchant
      summary: 'Create merchant'
      operationId: CreateMerchant
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMerchantRequest'
      responses:
        '201':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
  /merchants/{id}:
    get:
      tags:
        - Merchant
      summary: 'Get merchant'
      operationId: GetMerchant
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
    put:
      tags:
        - Merchant
      summary: 'Update merchant'
      operationId: UpdateMerchant
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Merchant'
      responses:
        '204':
          description: 'Success'
    delete:
      tags:
        - Merchant
      summary: 'Delete merchant'
      operationId: DeleteMerchant
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '204':
          description: 'Success'
  /merchants/{id}/password:
    put:
      tags:
        - Merchant
      summary: 'Update merchant password by core admin'
      operationId: UpdateMerchantPassword
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequest'
      responses:
        '204':
          description: 'Success'
  /merchants/{id}/members:
    get:
      tags:
        - Member
      summary: 'List members'
      operationId: ListMembers
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/Ordering'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberList'
    post:
      tags:
        - Member
      summary: 'Create member'
      operationId: CreateMember
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
      responses:
        '201':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
  /merchants/{id}/contact-form:
    post:
      tags:
        - Merchant
      summary: 'Send contact form'
      operationId: SendContactForm
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactForm'
      responses:
        '201':
          description: 'Success'
  /verification:
    post:
      tags:
        - Verification
      summary: 'Send verification code'
      operationId: SendVerificationCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVerificationCodeRequest'
      responses:
        '201':
          description: 'Created'
  /spaces:
    get:
      tags:
        - Space
      summary: 'List spaces'
      operationId: ListSpaces
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IndexParam'
        - $ref: '#/components/parameters/LimitParam'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceList'  
    post:
      tags:
        - Space
      summary: 'Create space'
      operationId: CreateSpace
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveSpaceRequest'
      responses:
        '201':
          description: 'Created'
  /spaces/{id}:
    get:
      tags:
        - Space
      summary: 'Get space'
      operationId: GetSpace
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
    put:
      tags:
        - Space
      summary: 'Update space'
      operationId: UpdateSpace
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveSpaceRequest'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
    delete:
      tags:
        - Space
      summary: 'Delete space'
      operationId: DeleteSpace
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '204':
          description: 'Success'
  /spaces/{id}/tables:
    get:
      tags:
        - Space
      summary: 'List tables'
      operationId: ListTables
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Table'
    post:
      tags:
        - Space
      summary: 'Create table'
      operationId: CreateTable
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveTableRequest'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: ApiKey
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SaveSpaceRequest:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
    Space:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
    SpaceList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Space'
        pagination:
          $ref: '#/components/schemas/Pagination'
    CreateVerificationCodeRequest:
      type: object
      properties:
        merchantId:
          type: string
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
    Member:
      type: object
      required:
        - id
        - merchantId
        - name
        - phoneNumber
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        merchantId:
          type: string
        name:
          type: string
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    MemberList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Member'
        pagination:
          $ref: '#/components/schemas/Pagination'
    CreateMerchantRequest:
      type: object
      required:
        - shortMerchantId
        - account
        - password
      properties:
        shortMerchantId:
          type: string
        account:
          type: string
        password:
          type: string
    Merchant:
      type: object
      required:
        - id
        - shortMerchantId
        - account
        - name
        - description
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        shortMerchantId:
          type: string
        account:
          type: string
        name:
          type: string
        description:
          type: string
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    MerchantList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Merchant'
        pagination:
          $ref: '#/components/schemas/Pagination'
    PhoneNumber:
      type: object
      required:
        - countryCode
        - number
      properties:
        countryCode:
          type: string
        number:
          type: string
    CreateSessionRequest:
      description: 'Login request'
      type: object
      properties:
        shortMerchantId:
          type: string
        account:
          type: string
        password:
          type: string
    CreateAdminRequest:
      description: 'Create admin request schema'
      required:
        - account
        - password
      type: object
      properties:
        account:
          type: string
        password:
          type: string
        role:
          $ref: '#/components/schemas/Role'
    Session:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    Role:
      type: string
      enum: [ROOT, ADMIN]
    UpdatePasswordRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
        oldPassword:
          type: string
    Ordering:
      description: 'Ordering'
      type: string
      enum: [ASCENDING, DESCENDING]
    Pagination:
      description: 'Pagination'
      type: object
      required:
        - index
        - limit
        - total
      properties:
        index:
          type: integer
          format: int64
          description: 'Current page'
        limit:
          type: integer
          format: int64
          description: 'Amount per page'
        total:
          type: integer
          format: int64
          description: 'Total page'
    ContactForm:
      type: object
      properties:
        name:
          type: string
        phone:
          $ref: '#/components/schemas/PhoneNumber'
        email:
          type: string
        subject:
          type: string
        message:
          type: string
    ContactFormList:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ContactForm'
        pagination:
          $ref: '#/components/schemas/Pagination'
    # Order
    SaveFoodRequest:
      type: object
      required:
        - name
        - description
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64
        fixedOffset:
          type: integer
          format: int64
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/FoodAttribute'
    Food:
      type: object
      required:
        - id
        - name
        - description
        - price
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64
        fixedOffset:
          type: integer
          format: int64
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/FoodAttribute'
    FoodAttribute:
      type: object
      required:
        - label
        - description
      properties:
        label:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/FoodAttributesOption'
    Period:
      type: object
      required:
        - startAt
        - endAt
      properties:
        startAt:
          type: integer
          format: int64
        endAt:
          type: integer
          format: int64
    FoodAttributesOption:
      type: object
      required:
        - label
      properties:
        label:
          type: string
        extra:
          type: integer
          format: int64
    Order:
      type: object
      required:
        - pickUpCode
        - foods
        - createdAt
        - updatedAt
      properties:
        tableLabel:
          type: string
        pickUpCode:
          type: string
        foods:
          type: array
          items:
            $ref: '#/components/schemas/Food'
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    SaveTableRequest:
      type: object
      required:
        - label
      properties:
        label:
          type: string
    Table:
      type: object
      required:
        - id
        - label
      properties:
        id:
          type: string
        label:
          type: string
  parameters:
    Ordering:
      name: ordering
      description: 'ASCENDING or DESCENDING'
      in: query
      schema:
        $ref: '#/components/schemas/Ordering'
    IndexParam:
      name: index
      in: query
      description: 'Current page index'
      schema:
        type: integer
        minimum: 0
        default: 0
    LimitParam:
      name: limit
      in: query
      description: 'Total pages'
      schema:
        type: integer
        minimum: 1
        default: 1
    ID:
      in: path
      name: id
      schema:
        type: string
      required: true
    StartAt:
      in: query
      name: startAt
      schema:
        type: integer
        format: int64
    EndAt:
      in: query
      name: endAt
      schema:
        type: integer
        format: int64