name: Publish Go Interfaces

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  REPOSITORY_NAME: merchant-api-interfaces
  EMAIL: "chenyunda218@gmail.com"
  GEN_VERSION: "21106e0"
  WECOM_WEBHOOK_URL: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f683698e-9790-42ef-a2be-25486a98e117"

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    name: Publish Go Interfaces
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.6"
      - name: Push to core-go-sdk
        run: |
          mkdir ${{env.REPOSITORY_NAME}}
          cd ${{env.REPOSITORY_NAME}}
          go mod init github.com/universalmacro/${{env.REPOSITORY_NAME}}
          go get github.com/gin-gonic/gin
          go install github.com/universalmacro/openapi-go-generator@${{env.GEN_VERSION}}
          go run github.com/universalmacro/openapi-go-generator@${{env.GEN_VERSION}} ../openapi.yml ${{env.REPOSITORY_NAME}} ./api.go
          git config --global user.email "${{env.EMAIL}}"
          git config --global user.name "Dan Chen"
          go env -w GOPRIVATE=github.com/universalmacro/*
          cp ../git_push.sh .
          sh git_push.sh ${{env.REPOSITORY_OWNER}} ${{env.REPOSITORY_NAME}} ${{ secrets.GIT_TOKEN }}
          git rev-parse HEAD
          cd ..
          sh go-interfaces-notification.sh ${{env.WECOM_WEBHOOK_URL}} ${{env.REPOSITORY_NAME}} `git rev-parse HEAD`
